### ISSUE TITLE
Versions and Hardware specs

### ISSUE THREAD

**Issue by lucy2329** [TempleRAIL/drl_vo_nav#1]
Hey, I was trying to run the baseline model that you have mentioned on the paper. I see that you're using a DGX-1, could you provide some information on how long it took. 
Also, stable-baselines3 has a pre req of torch > 1.11 as shown [here](https://stable-baselines3.readthedocs.io/en/master/guide/install.html). Is there a requirements.txt I can go off of?

**Comment by zzuxzt** [comment]
Thank you for your interest in our work. The ReadMe introduction is still under construction. I will update the code with more detailed information, requirements file, and add a container environment with required packages this weekeed. However, here is some information you may need: 
1. I only used 1 GPU in DGX-1 and it took about 1 week for training. 

2. The new vesion of stable-baseline3 needs torch > 1.11, but the old one does not require it. The detailed version information of learning packages is as follows, and you can add them to a requirements.txt to install:  
gym==0.18.0
pandas==1.2.1
stable-baselines3==1.1.0
torch==1.7.1

Or you can manually install them by the following commands:
pip install torch==1.7.1+cu110 -f https://download.pytorch.org/whl/torch_stable.html
pip install gym==0.18.0 pandas==1.2.1
pip install stable-baselines3==1.1.0
