### ISSUE TITLE
Simulation failure（Using singularity container）

### ISSUE THREAD

**Issue by Alchemistqqqq** [TempleRAIL/drl_vo_nav#12]
Hello, after reading your paper, I have developed a strong interest in drl_vo. I want to conduct the test in the simulation environment first, and then deploy it to the real vehicle for the experiment. However, I encountered the following problems in the simulation process, and I hope you can provide me with some help.rviz's maps and bots load slowly when I launch with containers, but after I wait for a while, the bots start moving when given the target point. However, when starting the simulation experiment, the terminal will prompt two errors, as shown in the figure below. I wonder whether it will have an impact on the simulation.
![drl_vo_error2](https://github.com/TempleRAIL/drl_vo_nav/assets/146717415/9c3bbf42-a7b7-4020-b636-9c928ff48f0d)

**Comment by zzuxzt** [comment]
Thanks for your interest in our work. Note that the yellow log messages are not errors but warning messages. I did not see anything wrong with your run, you just have to wait. Running speed depends on the computing resources on your computer (e.g. with/without GPU).
