### ISSUE TITLE
VO position in the code

### ISSUE THREAD

**Issue by Alchemistqqqq** [TempleRAIL/drl_vo_nav#13]
Hello, before the actual physics experiment, I hope to read the code to deepen my understanding of this work. You used VO in your paper and designed a new reward function based on it. Perhaps due to carelessness, I can't locate it accurately in the code. I hope you can provide some help, thank you very much.

**Comment by zzuxzt** [comment]
Thank you for your interest in our work. The detailed implementation is in [theta_reward](https://github.com/TempleRAIL/drl_vo_nav/blob/7a3d8f9be2963ebacdaad4b676aa5de3a8c5d9ce/drl_vo/src/turtlebot_gym/turtlebot_gym/envs/drl_nav_env.py#L1010).
