### ISSUE TITLE
The meaning of values contained in /map topic

### ISSUE THREAD

**Issue by alantes** [TempleRAIL/drl_vo_nav#14]
Dear researcher,

Thank you for your fantastic work. I am working on running your project. However, the messages received by /map seems not meaningful. In a map that is almost empty, the map.data I received is almost full of -1. If I understand it correctly, value 0 stands for open space without obstacles. So what is the meaning of -1 and 100:

<img width="650" alt="294159432-317a303b-fe77-418e-93b4-dd1b1e510690" src="https://github.com/TempleRAIL/drl_vo_nav/assets/13460765/aec1c4aa-fefd-4863-871d-7cba62d3becf">

**Comment by WIT23** [comment]
The map is loaded from a pgm format file. 100 means obstacle and -1 means no information.

**Comment by alantes** [comment]
Thanks a lot for your clarification!
