### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by kai-zhang-er** [TempleRAIL/drl_vo_nav#20]
Hello,

Great work!
I'm willing to compare my algorithm with yours. Is it possible to share your pretrained model?
Thank you in advance!

Best,
Kai

**Comment by zzuxzt** [comment]
Thanks for your interest in our work. The trained model is already in this repository: [drl_vo.zip](https://github.com/TempleRAIL/drl_vo_nav/blob/baa970c30cabe94a8b0eb81bb0ad0b97261f2458/drl_vo/src/model/drl_vo.zip). Please read the ReadMe in this repository to learn more.

**Comment by kai-zhang-er** [comment]
Thank you!
