### ISSUE TITLE
Issue with Loading "Square" Map File in Gazebo

### ISSUE THREAD

**Issue by AwsSleepy** [TempleRAIL/drl_vo_nav#24]
@zzuxzt Hello! Thanks for your great work.

I could not find a map file named "square," and I attempted to modify the launch file as follows:

```xml
<arg name="scene_file" default="$(find pedsim_simulator)/scenarios/square/new_25_v1.xml"/>
<arg name="world_name" default="$(find pedsim_gazebo_plugin)/worlds/nav_test.world"/>
<arg name="gui" default="true" doc="Bring up the Gazebo graphical interface"/>
<!-- lobby: (1,1); square: (1,1); cumberland: (4,8); autolab: (1,8); freiburg: (3,17) -->
<arg name="pose_initial_x" default="1.0"/> 
<arg name="pose_initial_y" default="1.0"/>
<arg name="map_file" default="$(find robot_gazebo)/maps/gazebo_new_world/gazebo_new_world.yaml"/>
<!-- Localization: lobby:(1,0,0.13), others:(0,0,0) -->
<arg name="initial_pose_x" default="0.0"/>
<arg name="initial_pose_y" default="0.0"/>
<arg name="initial_pose_a" default="0.0"/>
<arg name="model_file" default="$(find drl_vo_nav)/src/model/drl_vo.zip"/>
```

However, in RViz, the map does not visualize correctly, and there is a large black area where the map should be. Additionally, when I send a goal to the robot within this black area, it doesn't move toward the target. 

![image](https://github.com/TempleRAIL/drl_vo_nav/assets/102525193/e1905777-8fd0-4252-a5bd-8d996ea4c5ba)

How can I correctly load the "square" map in Gazebo and ensure proper visualization in RViz?

 Any guidance on this issue would be appreciated.

**Comment by zzuxzt** [comment]
That is the right map for the Square world and your rviz visualization is correct. Note that black cells in the occupancy grid map means they are occupied, and that black mask is manually added to prevent robots from moving there.

**Comment by AwsSleepy** [comment]
Thank you!
