### ISSUE TITLE
Demo bug ?

### ISSUE THREAD

**Issue by yimengweima0** [TempleRAIL/drl_vo_nav#31]
Hello, thank you very much for your work. When I run your navigation file，Is it normal for the robot to shake that much? just like this
https://github.com/user-attachments/assets/13234c0f-9ec3-4c40-a9b0-f74db425e92a

**Comment by yimengweima0** [comment]
just like this 
https://github.com/user-attachments/assets/13234c0f-9ec3-4c40-a9b0-f74db425e92a

**Comment by yimengweima0** [comment]
When I didn't change anything and just ported the code to Melodic, the robot still shake that much.

started roslaunch server http://localhost:37401/

SUMMARY
========

PARAMETERS
 * /amcl/base_frame_id: base_footprint
 * /amcl/global_frame_id: map
 * /amcl/gui_publish_rate: 10.0
 * /amcl/initial_pose_a: 0.13
 * /amcl/initial_pose_x: 1.0
 * /amcl/initial_pose_y: 0.0
 * /amcl/kld_err: 0.05
 * /amcl/kld_z: 0.99
 * /amcl/laser_lambda_short: 0.1
 * /amcl/laser_likelihood_max_dist: 2.0
 * /amcl/laser_max_beams: 60
 * /amcl/laser_max_range: 12.0
 * /amcl/laser_model_type: likelihood_field
 * /amcl/laser_sigma_hit: 0.2
 * /amcl/laser_z_hit: 0.5
 * /amcl/laser_z_max: 0.05
 * /amcl/laser_z_rand: 0.5
 * /amcl/laser_z_short: 0.05
 * /amcl/max_particles: 2000
 * /amcl/min_particles: 500
 * /amcl/odom_alpha1: 0.2
 * /amcl/odom_alpha2: 0.2
 * /amcl/odom_alpha3: 0.2
 * /amcl/odom_alpha4: 0.2
 * /amcl/odom_alpha5: 0.1
 * /amcl/odom_frame_id: odom
 * /amcl/odom_model_type: diff
 * /amcl/recovery_alpha_fast: 0.0
 * /amcl/recovery_alpha_slow: 0.0
 * /amcl/resample_interval: 1
 * /amcl/transform_tolerance: 1.0
 * /amcl/update_min_a: 0.2
 * /amcl/update_min_d: 0.25
 * /amcl/use_map_topic: False
 * /bumper2pointcloud/pointcloud_radius: 0.24
 * /cmd_vel_mux/yaml_cfg_file: /home/lwh/G314/ro...
 * /drl_vo_cmd/model_file: /home/lwh/G314/co...
 * /gazebo/enable_ros_network: True
 * /move_base/DWAPlannerROS/acc_lim_theta: 2.0
 * /move_base/DWAPlannerROS/acc_lim_x: 1.0
 * /move_base/DWAPlannerROS/acc_lim_y: 1.0
 * /move_base/DWAPlannerROS/forward_point_distance: 0.5
 * /move_base/DWAPlannerROS/global_frame_id: odom
 * /move_base/DWAPlannerROS/goal_distance_bias: 24.0
 * /move_base/DWAPlannerROS/max_scaling_factor: 0.2
 * /move_base/DWAPlannerROS/max_vel_rot: 3.0
 * /move_base/DWAPlannerROS/max_vel_trans: 0.5
 * /move_base/DWAPlannerROS/max_vel_x: 0.5
 * /move_base/DWAPlannerROS/max_vel_y: 0.0
 * /move_base/DWAPlannerROS/min_vel_rot: 0.4
 * /move_base/DWAPlannerROS/min_vel_trans: 0.1
 * /move_base/DWAPlannerROS/min_vel_x: 0.0
 * /move_base/DWAPlannerROS/min_vel_y: 0.0
 * /move_base/DWAPlannerROS/occdist_scale: 0.5
 * /move_base/DWAPlannerROS/oscillation_reset_dist: 0.05
 * /move_base/DWAPlannerROS/path_distance_bias: 64.0
 * /move_base/DWAPlannerROS/publish_cost_grid_pc: True
 * /move_base/DWAPlannerROS/publish_traj_pc: True
 * /move_base/DWAPlannerROS/scaling_speed: 0.25
 * /move_base/DWAPlannerROS/sim_time: 1.0
 * /move_base/DWAPlannerROS/stop_time_buffer: 0.2
 * /move_base/DWAPlannerROS/theta_stopped_vel: 0.4
 * /move_base/DWAPlannerROS/trans_stopped_vel: 0.1
 * /move_base/DWAPlannerROS/vtheta_samples: 20
 * /move_base/DWAPlannerROS/vx_samples: 6
 * /move_base/DWAPlannerROS/vy_samples: 1
 * /move_base/DWAPlannerROS/xy_goal_tolerance: 0.9
 * /move_base/DWAPlannerROS/yaw_goal_tolerance: 6.28
 * /move_base/GlobalPlanner/allow_unknown: True
 * /move_base/GlobalPlanner/cost_factor: 3.0
 * /move_base/GlobalPlanner/default_tolerance: 0.3
 * /move_base/GlobalPlanner/lethal_cost: 253
 * /move_base/GlobalPlanner/neutral_cost: 50
 * /move_base/GlobalPlanner/old_navfn_behavior: False
 * /move_base/GlobalPlanner/planner_costmap_publish_frequency: 0.0
 * /move_base/GlobalPlanner/planner_window_x: 0.0
 * /move_base/GlobalPlanner/planner_window_y: 0.0
 * /move_base/GlobalPlanner/publish_potential: True
 * /move_base/GlobalPlanner/publish_scale: 100
 * /move_base/GlobalPlanner/use_dijkstra: True
 * /move_base/GlobalPlanner/use_grid_path: False
 * /move_base/GlobalPlanner/use_quadratic: True
 * /move_base/NavfnROS/allow_unknown: False
 * /move_base/NavfnROS/default_tolerance: 0.3
 * /move_base/NavfnROS/planner_window_x: 0.0
 * /move_base/NavfnROS/planner_window_y: 0.0
 * /move_base/NavfnROS/visualize_potential: False
 * /move_base/base_global_planner: navfn/NavfnROS
 * /move_base/base_local_planner: dwa_local_planner...
 * /move_base/controller_frequency: 5.0
 * /move_base/controller_patience: 3.0
 * /move_base/global_costmap/global_frame: map
 * /move_base/global_costmap/inflation_layer/cost_scaling_factor: 5.0
 * /move_base/global_costmap/inflation_layer/enabled: True
 * /move_base/global_costmap/inflation_layer/inflation_radius: 0.5
 * /move_base/global_costmap/map_type: voxel
 * /move_base/global_costmap/max_obstacle_height: 0.6
 * /move_base/global_costmap/obstacle_layer/bump/clearing: False
 * /move_base/global_costmap/obstacle_layer/bump/data_type: PointCloud2
 * /move_base/global_costmap/obstacle_layer/bump/marking: True
 * /move_base/global_costmap/obstacle_layer/bump/max_obstacle_height: 0.15
 * /move_base/global_costmap/obstacle_layer/bump/min_obstacle_height: 0.0
 * /move_base/global_costmap/obstacle_layer/bump/topic: mobile_base/senso...
 * /move_base/global_costmap/obstacle_layer/combination_method: 1
 * /move_base/global_costmap/obstacle_layer/enabled: True
 * /move_base/global_costmap/obstacle_layer/mark_threshold: 0
 * /move_base/global_costmap/obstacle_layer/max_obstacle_height: 0.6
 * /move_base/global_costmap/obstacle_layer/observation_sources: scan bump
 * /move_base/global_costmap/obstacle_layer/obstacle_range: 2.5
 * /move_base/global_costmap/obstacle_layer/origin_z: 0.0
 * /move_base/global_costmap/obstacle_layer/publish_voxel_map: False
 * /move_base/global_costmap/obstacle_layer/raytrace_range: 3.0
 * /move_base/global_costmap/obstacle_layer/scan/clearing: True
 * /move_base/global_costmap/obstacle_layer/scan/data_type: LaserScan
 * /move_base/global_costmap/obstacle_layer/scan/marking: True
 * /move_base/global_costmap/obstacle_layer/scan/max_obstacle_height: 0.35
 * /move_base/global_costmap/obstacle_layer/scan/min_obstacle_height: 0.15
 * /move_base/global_costmap/obstacle_layer/scan/topic: scan
 * /move_base/global_costmap/obstacle_layer/track_unknown_space: True
 * /move_base/global_costmap/obstacle_layer/unknown_threshold: 15
 * /move_base/global_costmap/obstacle_layer/z_resolution: 0.2
 * /move_base/global_costmap/obstacle_layer/z_voxels: 2
 * /move_base/global_costmap/plugins: [{'type': 'costma...
 * /move_base/global_costmap/publish_frequency: 0.5
 * /move_base/global_costmap/robot_base_frame: base_footprint
 * /move_base/global_costmap/robot_radius: 0.2
 * /move_base/global_costmap/static_layer/enabled: True
 * /move_base/global_costmap/static_map: True
 * /move_base/global_costmap/transform_tolerance: 0.5
 * /move_base/global_costmap/update_frequency: 1.0
 * /move_base/local_costmap/global_frame: odom
 * /move_base/local_costmap/height: 4.0
 * /move_base/local_costmap/inflation_layer/cost_scaling_factor: 5.0
 * /move_base/local_costmap/inflation_layer/enabled: True
 * /move_base/local_costmap/inflation_layer/inflation_radius: 0.5
 * /move_base/local_costmap/map_type: voxel
 * /move_base/local_costmap/max_obstacle_height: 0.6
 * /move_base/local_costmap/obstacle_layer/bump/clearing: False
 * /move_base/local_costmap/obstacle_layer/bump/data_type: PointCloud2
 * /move_base/local_costmap/obstacle_layer/bump/marking: True
 * /move_base/local_costmap/obstacle_layer/bump/max_obstacle_height: 0.15
 * /move_base/local_costmap/obstacle_layer/bump/min_obstacle_height: 0.0
 * /move_base/local_costmap/obstacle_layer/bump/topic: mobile_base/senso...
 * /move_base/local_costmap/obstacle_layer/combination_method: 1
 * /move_base/local_costmap/obstacle_layer/enabled: True
 * /move_base/local_costmap/obstacle_layer/mark_threshold: 0
 * /move_base/local_costmap/obstacle_layer/max_obstacle_height: 0.6
 * /move_base/local_costmap/obstacle_layer/observation_sources: scan bump
 * /move_base/local_costmap/obstacle_layer/obstacle_range: 2.5
 * /move_base/local_costmap/obstacle_layer/origin_z: 0.0
 * /move_base/local_costmap/obstacle_layer/publish_voxel_map: False
 * /move_base/local_costmap/obstacle_layer/raytrace_range: 3.0
 * /move_base/local_costmap/obstacle_layer/scan/clearing: True
 * /move_base/local_costmap/obstacle_layer/scan/data_type: LaserScan
 * /move_base/local_costmap/obstacle_layer/scan/marking: True
 * /move_base/local_costmap/obstacle_layer/scan/max_obstacle_height: 0.35
 * /move_base/local_costmap/obstacle_layer/scan/min_obstacle_height: 0.15
 * /move_base/local_costmap/obstacle_layer/scan/topic: scan
 * /move_base/local_costmap/obstacle_layer/track_unknown_space: True
 * /move_base/local_costmap/obstacle_layer/unknown_threshold: 15
 * /move_base/local_costmap/obstacle_layer/z_resolution: 0.2
 * /move_base/local_costmap/obstacle_layer/z_voxels: 2
 * /move_base/local_costmap/plugins: [{'type': 'costma...
 * /move_base/local_costmap/publish_frequency: 2.0
 * /move_base/local_costmap/resolution: 0.05
 * /move_base/local_costmap/robot_base_frame: base_footprint
 * /move_base/local_costmap/robot_radius: 0.2
 * /move_base/local_costmap/rolling_window: True
 * /move_base/local_costmap/static_layer/enabled: True
 * /move_base/local_costmap/static_map: False
 * /move_base/local_costmap/transform_tolerance: 0.5
 * /move_base/local_costmap/update_frequency: 5.0
 * /move_base/local_costmap/width: 4.0
 * /move_base/oscillation_distance: 0.2
 * /move_base/oscillation_timeout: 10.0
 * /move_base/planner_frequency: 1.0
 * /move_base/planner_patience: 5.0
 * /move_base/shutdown_costmaps: False
 * /navigation_velocity_smoother/accel_lim_v: 1.0
 * /navigation_velocity_smoother/accel_lim_w: 2.0
 * /navigation_velocity_smoother/decel_factor: 1.5
 * /navigation_velocity_smoother/frequency: 20.0
 * /navigation_velocity_smoother/robot_feedback: 2
 * /navigation_velocity_smoother/speed_lim_v: 0.8
 * /navigation_velocity_smoother/speed_lim_w: 5.4
 * /pedsim_simulator/default_queue_size: 10
 * /pedsim_simulator/enable_groups: True
 * /pedsim_simulator/frame_id: gazebo
 * /pedsim_simulator/max_robot_speed: 1.5
 * /pedsim_simulator/robot_mode: 1
 * /pedsim_simulator/scene_file: /home/lwh/G314/co...
 * /pedsim_simulator/simulation_factor: 1.0
 * /pedsim_simulator/update_rate: 25.0
 * /pure_pursuit/rate: 20.0
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 30.0
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /teleop_velocity_smoother/accel_lim_v: 1.0
 * /teleop_velocity_smoother/accel_lim_w: 2.0
 * /teleop_velocity_smoother/decel_factor: 1.5
 * /teleop_velocity_smoother/frequency: 20.0
 * /teleop_velocity_smoother/robot_feedback: 2
 * /teleop_velocity_smoother/speed_lim_v: 0.8
 * /teleop_velocity_smoother/speed_lim_w: 5.4
 * /use_sim_time: True

NODES
  /
    amcl (amcl/amcl)
    bumper2pointcloud (nodelet/nodelet)
    cmd_vel_mux (nodelet/nodelet)
    cnn_data_pub (drl_vo_nav/cnn_data_pub.py)
    drl_vo_cmd (drl_vo_nav/drl_vo_inference.py)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    gazebo_map_broadcaster (tf/static_transform_publisher)
    goal_visualize (drl_vo_nav/goal_visualize.py)
    kobuki_safety_controller (nodelet/nodelet)
    map_server (map_server/map_server)
    mix_cmd_vel (drl_vo_nav/cmd_vel_pub.py)
    mobile_base_nodelet_manager (nodelet/nodelet)
    move_base (move_base/move_base)
    navigation_velocity_smoother (nodelet/nodelet)
    pedsim_simulator (pedsim_simulator/pedsim_simulator)
    pedsim_visualizer (pedsim_visualizer/pedsim_visualizer_node)
    pure_pursuit (drl_vo_nav/pure_pursuit.py)
    robot_pose_pub (drl_vo_nav/robot_pose_pub.py)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)
    spawn_pedsim_agents (pedsim_gazebo_plugin/spawn_pedsim_agents.py)
    spawn_turtlebot_model (gazebo_ros/spawn_model)
    teleop_velocity_smoother (nodelet/nodelet)
    track_ped_pub (drl_vo_nav/track_ped_pub.py)

auto-starting new master
process[master]: started with pid [45690]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to dc3799ee-979e-11ef-9d0b-6c2b59ced16c
process[rosout-1]: started with pid [45701]
started core service [/rosout]
process[gazebo-2]: started with pid [45708]
process[gazebo_gui-3]: started with pid [45712]
process[spawn_pedsim_agents-4]: started with pid [45715]
process[gazebo_map_broadcaster-5]: started with pid [45719]
process[spawn_turtlebot_model-6]: started with pid [45720]
process[mobile_base_nodelet_manager-7]: started with pid [45726]
process[cmd_vel_mux-8]: started with pid [45727]
process[bumper2pointcloud-9]: started with pid [45728]
process[robot_state_publisher-10]: started with pid [45733]
process[pedsim_simulator-11]: started with pid [45739]
process[pedsim_visualizer-12]: started with pid [45741]
process[map_server-13]: started with pid [45751]
process[amcl-14]: started with pid [45821]
process[navigation_velocity_smoother-15]: started with pid [45826]
process[kobuki_safety_controller-16]: started with pid [45840]
process[move_base-17]: started with pid [45848]
process[pure_pursuit-18]: started with pid [45850]
process[cnn_data_pub-19]: started with pid [45855]
process[robot_pose_pub-20]: started with pid [45859]
process[track_ped_pub-21]: started with pid [45863]
process[goal_visualize-22]: started with pid [45870]
process[teleop_velocity_smoother-23]: started with pid [45874]
process[drl_vo_cmd-24]: started with pid [45875]
process[mix_cmd_vel-25]: started with pid [45878]
process[rviz-26]: started with pid [45886]
[ INFO] [1730389405.397940821]: Updated sim with live config: Rate=25 incoming rate=25
[ WARN] [1730389405.441671571]: Request for map failed; trying again...
[ INFO] [1730389405.461755803]: Using default queue size of 10 for publisher queues... 
[ INFO] [1730389405.494308871]: Loading scene [/home/lwh/G314/comparison/drl/src/pedsim_ros_with_gazebo/pedsim_simulator/scenarios/eng_hall.xml] for simulation
[ INFO] [1730389405.506958719]: node initialized, now running 
Waiting for gazebo services...
[ INFO] [1730389405.975796541]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1730389405.978790185]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1730389406.044633624]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1730389406.046929053]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[WARN] [1730389406.206388, 0.000000]: Could not get robot pose
[ INFO] [1730389410.311878218]: waitForService: Service [/gazebo/set_physics_properties] is now available.
service: spawn_sdf_model is available ....
[ INFO] [1730389410.429057053, 0.038000000]: Physics dynamic reconfigure ready.
[WARN] [1730389410.572603, 0.175000]: Could not get robot pose
[WARN] [1730389410.575567, 0.178000]: Could not get robot pose
[ INFO] [1730389410.959635102, 0.195000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1730389410.977634731, 0.195000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1730389411.468699952, 0.195000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1730389411.469191573, 0.195000000]: Starting Laser Plugin (ns = /)
[ INFO] [1730389411.472849284, 0.195000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[INFO] [1730389411.490945, 0.195000]: Spawning model: actor_id = 1
[ INFO] [1730389411.501619113, 0.195000000]: Starting plugin Kobuki(ns = //)
[ WARN] [1730389411.501678525, 0.195000000]: Kobuki(ns = //): missing <rosDebugLevel> default is na
[ INFO] [1730389411.502623449, 0.195000000]: Kobuki(ns = //): <tf_prefix> = 
[ WARN] [1730389411.503093284, 0.195000000]: Kobuki(ns = //): missing <update_rate> default is 0
[ INFO] [1730389411.503242895, 0.195000000]: Will publish tf. [mobile_base]
[ INFO] [1730389411.504946851, 0.195000000]: Kobuki(ns = //): Advertise joint_states[joint_states]!
[ INFO] [1730389411.507038768, 0.195000000]: Kobuki(ns = //): Advertise Odometry[odom]!
[ INFO] [1730389411.513458430, 0.195000000]: Kobuki(ns = //): Try to subscribe to mobile_base/commands/motor_power!
[ INFO] [1730389411.521858760, 0.195000000]: Kobuki(ns = //): Try to subscribe to mobile_base/commands/reset_odometry!
[ INFO] [1730389411.527048872, 0.195000000]: Kobuki(ns = //): Try to subscribe to mobile_base/commands/velocity!
[ INFO] [1730389411.528497529, 0.195000000]: Kobuki(ns = //): Advertise Cliff[mobile_base/events/cliff]!
[ INFO] [1730389411.529612108, 0.195000000]: Kobuki(ns = //): Advertise Bumper[mobile_base/events/bumper]!
[ INFO] [1730389411.531546044, 0.195000000]: Kobuki(ns = //): Advertise Wheel Drop[mobile_base/events/wheel_drop]!
[ INFO] [1730389411.532793264, 0.195000000]: Kobuki(ns = //): Advertise IMU[mobile_base/sensors/imu_data]!
[ INFO] [1730389411.535054364, 0.195000000]: Kobuki(ns = //): Advertise Core[mobile_base/sensors/core]!
[ INFO] [1730389411.535083079, 0.195000000]: GazeboRosKobuki plugin ready to go! [mobile_base]
[WARN] [1730389411.558376, 0.215000]: Could not get robot pose
[WARN] [1730389411.601817, 0.245000]: Could not get robot pose
Finish loading model.
[WARN] [1730389411.664254, 0.283000]: Could not get robot pose
[WARN] [1730389411.706955, 0.312000]: Could not get robot pose
[INFO] [1730389411.781595, 0.328000]: Spawning model: actor_id = 2
[spawn_turtlebot_model-6] process has finished cleanly
log file: /home/lwh/.ros/log/dc3799ee-979e-11ef-9d0b-6c2b59ced16c/spawn_turtlebot_model-6*.log
[WARN] [1730389412.202959, 0.358000]: Could not get robot pose
[WARN] [1730389412.232776, 0.378000]: Could not get robot pose
[WARN] [1730389412.274166, 0.412000]: Could not get robot pose
[WARN] [1730389412.320379, 0.445000]: Could not get robot pose
[INFO] [1730389412.406822, 0.476000]: Spawning model: actor_id = 3
[WARN] [1730389412.473051, 0.494000]: Could not get robot pose
[WARN] [1730389412.504045, 0.513000]: Could not get robot pose
[WARN] [1730389412.552469, 0.545000]: Could not get robot pose
[WARN] [1730389412.623035, 0.578000]: Could not get robot pose
[INFO] [1730389412.688301, 0.589000]: Spawning model: actor_id = 4
[WARN] [1730389412.795517, 0.612000]: Could not get robot pose
[WARN] [1730389412.840974, 0.645000]: Could not get robot pose
[WARN] [1730389412.885783, 0.678000]: Could not get robot pose
[INFO] [1730389412.980217, 0.687000]: Spawning model: actor_id = 5
[WARN] [1730389413.097689, 0.712000]: Could not get robot pose
[WARN] [1730389413.154767, 0.745000]: Could not get robot pose
[WARN] [1730389413.244941, 0.780000]: Could not get robot pose
[INFO] [1730389413.274810, 0.780000]: Spawning model: actor_id = 6
[WARN] [1730389413.383611, 0.812000]: Could not get robot pose
[WARN] [1730389413.432590, 0.846000]: Could not get robot pose
[WARN] [1730389413.481586, 0.878000]: Could not get robot pose
[INFO] [1730389413.555389, 0.905000]: Spawning model: actor_id = 7
[WARN] [1730389413.667586, 0.912000]: Could not get robot pose
[INFO] [1730389413.834431, 0.929000]: Spawning model: actor_id = 8
[INFO] [1730389414.110235, 0.934000]: Spawning model: actor_id = 9
[INFO] [1730389414.416764, 0.939000]: Spawning model: actor_id = 10
[INFO] [1730389414.722641, 0.944000]: Spawning model: actor_id = 11
[WARN] [1730389414.799671, 0.945000]: Could not get robot pose
[INFO] [1730389415.001166, 0.949000]: Spawning model: actor_id = 12
[INFO] [1730389415.281408, 0.953000]: Spawning model: actor_id = 13
[INFO] [1730389415.578950, 0.957000]: Spawning model: actor_id = 14
[INFO] [1730389415.871004, 0.961000]: Spawning model: actor_id = 15
[INFO] [1730389416.237311, 0.965000]: Spawning model: actor_id = 16
[INFO] [1730389416.557613, 0.969000]: Spawning model: actor_id = 17
[INFO] [1730389416.873631, 0.973000]: Spawning model: actor_id = 18
[INFO] [1730389417.182705, 0.977000]: Spawning model: actor_id = 19
[WARN] [1730389417.275303, 0.978000]: Could not get robot pose
[INFO] [1730389417.465790, 0.981000]: Spawning model: actor_id = 20
[INFO] [1730389417.759074, 0.989000]: Spawning model: actor_id = 21
[INFO] [1730389418.050841, 0.997000]: Spawning model: actor_id = 22
[INFO] [1730389418.331231, 1.005000]: Spawning model: actor_id = 23
[WARN] [1730389418.525149, 1.012000]: Could not get robot pose
[INFO] [1730389418.613298, 1.015000]: Spawning model: actor_id = 24
[INFO] [1730389418.900593, 1.026000]: Spawning model: actor_id = 25
[INFO] [1730389419.171192, 1.035000]: Spawning model: actor_id = 26
[INFO] [1730389419.455594, 1.042000]: Spawning model: actor_id = 27
[WARN] [1730389419.564170, 1.045000]: Could not get robot pose
[INFO] [1730389419.727641, 1.050000]: Spawning model: actor_id = 28
[INFO] [1730389420.011492, 1.058000]: Spawning model: actor_id = 29
[INFO] [1730389420.285512, 1.067000]: Spawning model: actor_id = 30
[INFO] [1730389420.564861, 1.076000]: Spawning model: actor_id = 31
[WARN] [1730389420.649187, 1.078000]: Could not get robot pose
[INFO] [1730389420.840931, 1.085000]: Spawning model: actor_id = 32
[INFO] [1730389421.111786, 1.094000]: Spawning model: actor_id = 33
[INFO] [1730389421.406721, 1.102000]: Spawning model: actor_id = 34
[WARN] [1730389421.777323, 1.112000]: Could not get robot pose
[spawn_pedsim_agents-4] process has finished cleanly
log file: /home/lwh/.ros/log/dc3799ee-979e-11ef-9d0b-6c2b59ced16c/spawn_pedsim_agents-4*.log
[WARN] [1730389422.845267, 1.146000]: Could not get robot pose
[WARN] [1730389423.226335, 1.179000]: Could not get robot pose
[WARN] [1730389423.581632, 1.212000]: Could not get robot pose
[WARN] [1730389423.956079, 1.245000]: Could not get robot pose
[WARN] [1730389424.322461, 1.287000]: Could not get robot pose
[WARN] [1730389424.363764, 1.317000]: Could not get robot pose
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
[ WARN] [1730389424.392123418, 1.337000000]: global_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ WARN] [1730389424.394863380, 1.337000000]: global_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided
[ INFO] [1730389424.397197453, 1.347000000]: global_costmap: Using plugin "static_layer"
[ INFO] [1730389424.414541111, 1.357000000]: Requesting the map...
[ INFO] [1730389424.566460154, 1.467000000]: Resizing costmap to 1024 X 768 at 0.050000 m/pix
[ INFO] [1730389424.679770352, 1.567000000]: Received a 1024 X 768 map at 0.050000 m/pix
[ INFO] [1730389424.688993853, 1.567000000]: global_costmap: Using plugin "obstacle_layer"
[ INFO] [1730389424.698312331, 1.577000000]:     Subscribed to Topics: scan bump
[ INFO] [1730389424.783875188, 1.647000000]: global_costmap: Using plugin "inflation_layer"
[ WARN] [1730389424.891924611, 1.757000000]: local_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ WARN] [1730389424.893128168, 1.757000000]: local_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided
[ INFO] [1730389424.894434561, 1.757000000]: local_costmap: Using plugin "obstacle_layer"
[ INFO] [1730389424.902974849, 1.757000000]:     Subscribed to Topics: scan bump
[ INFO] [1730389424.976042320, 1.827000000]: local_costmap: Using plugin "inflation_layer"
[ INFO] [1730389425.041436125, 1.887000000]: Created local_planner dwa_local_planner/DWAPlannerROS
[ INFO] [1730389425.048359901, 1.897000000]: Sim period is set to 0.20
[ INFO] [1730389425.241159064, 2.087000000]: Recovery behavior will clear layer 'obstacles'
[ INFO] [1730389425.252043990, 2.097000000]: Recovery behavior will clear layer 'obstacles'
[ INFO] [1730389425.399268784, 2.247000000]: odom received!
[ WARN] [1730389428.297095056, 5.007000000]: Covariance matrix is not positive (semi-)definite in ProbabilityEllipseCovarianceVisual::setMeanCovariance(): Matrix3(0, 0, 0, 0, 0, 0, 0, 0, 0)
[ WARN] [1730389433.927486600, 10.037000000]: Covariance matrix is not positive (semi-)definite in ProbabilityEllipseCovarianceVisual::setMeanCovariance(): Matrix3(0, 0, 0, 0, 0, 0, 0, 0, 0)
[ WARN] [1730389439.461948374, 15.037000000]: Covariance matrix is not positive (semi-)definite in ProbabilityEllipseCovarianceVisual::setMeanCovariance(): Matrix3(0, 0, 0, 0, 0, 0, 0, 0, 0)
[ INFO] [1730389440.482105724, 15.807000000]: Got new plan
[ INFO] [1730389441.756424795, 16.807000000]: Got new plan

**Comment by yimengweima0** [comment]
Could you please assist me in resolving them? I would really appreciate your guidance. Thank you!" @zzuxzt

**Comment by zzuxzt** [comment]
Modify lines 133-134 of [drl_vo_inference.py](https://github.com/TempleRAIL/drl_vo_nav/blob/baa970c30cabe94a8b0eb81bb0ad0b97261f2458/drl_vo/src/drl_vo_inference.py#L133C1-L134C29) as follows::
`
vz_min = -0.7
`
`
vz_max = 0.7
`

**Comment by yimengweima0** [comment]
ok, thank you
