### ISSUE TITLE
Can not run the navigation_demo

### ISSUE THREAD

**Issue by XinJingHao** [TempleRAIL/drl_vo_nav#32]
Hi, I followed the `singularity container` instruction.
Everything seems to be smooth except when I run the final command`sh run_drl_vo_navigation_demo.sh` 

It shows:
`[ WARN] [1732091475.387135358]: Request for map failed; trying again...`
...
`[WARN] [1732091475.485157121]: Could not get robot pose`
...
`[ WARN] [1732091240.418704039]: OGRE EXCEPTION(3:RenderingAPIException): Unable to create a suitable GLXContext in GLXContext::GLXContext at /build/ogre-1.9-kiU5_5/ogre-1.9-1.9.0+dfsg1/RenderSystems/GL/src/GLX/OgreGLXContext.cpp (line 61)`
...
`[ERROR] [1732091240.419849112]: Unable to create the rendering window after 100 tries.`
...
`[rviz-26] process has died [pid 160970, exit code -6, cmd /opt/ros/noetic/lib/rviz/rviz -d /home/roscenter/catkin_ws/src/robot_gazebo/rviz/navigation.rviz __name:=rviz __log:=/home/roscenter/.ros/log/2d3d5f84-a719-11ef-9fe6-2cf05d2157f8/rviz-26.log].
log file: /home/roscenter/.ros/log/2d3d5f84-a719-11ef-9fe6-2cf05d2157f8/rviz-26*.log`

My system is:
Ubuntu 20.04
Nvidia 3060(Driver Version: 550.120        CUDA Version: 12.4)
ROS noetic
gazebo: 11.11.0
rviz:1.14.25

**Comment by zzuxzt** [comment]
Reboot your computer.
