### ISSUE TITLE
Sensor topic /cnn_data is not available，Sensor topic /map is not available Couldn't find the left cliff sensor in the model! 

### ISSUE THREAD

**Issue by panzhangchao** [TempleRAIL/drl_vo_nav#33]
![2024-12-01 08-48-39 的屏幕截图](https://github.com/user-attachments/assets/8384f35a-23e4-4fad-ac8b-3ddd74693f78)
![2024-12-01 08-49-43 的屏幕截图](https://github.com/user-attachments/assets/007af03a-f470-4d99-a011-ea4634f633cc)

When I run "sh run_drl_vo_policy_training_server.sh ~/drl_vo_runs", I encountered the error shown in the above image, but when I ran "rostopin info/cnn.data", the following image appeared. May I ask if this is related to the network.
![2024-12-01 08-52-16 的屏幕截图](https://github.com/user-attachments/assets/5c5edd32-a0b8-4853-892c-07bcb30fe059)

Thanks very much

**Comment by DavidYan628** [comment]
Hello, I encountered the same problem when I ran "sh run_drl_vo_policy_training_server.sh ~/drl_vo_runs". How did you solve it?

**Comment by HS678** [comment]
> Hello, I encountered the same problem when I ran "sh run_drl_vo_policy_training_server.sh ~/drl_vo_runs". How did you solve it?

I also encountered the problem.Do you solve it?And how to solve ?

**Comment by shaashou** [comment]
I also encountered the problem.Do you solve it?And how to solve ?
