### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by DavidYan628** [TempleRAIL/drl_vo_nav#35]
![1733362384613](https://github.com/user-attachments/assets/d3b038b8-d8bb-464b-8476-e689154ee5b5)
![1733362700883](https://github.com/user-attachments/assets/58cfb29e-052f-4a7c-825c-d2a73b7b3c8d)
There was an issue while building the spencer_tracking_rviz_plugin plugin in the pedsim_ros_with_gazebo package. The error occurred when compiling the target spencer_tracking_rviz_plugin, specifically while building tracked_groups_display.cpp.o
How can I solve this problem?
My system is:
Ubuntu 20.04
ROS noetic
Python 3.8.5 Python 3.8.5 版
Pytorch 1.7.1
gazebo 11.11.0
rviz  1.14.25
Qt  5.15.2

**Comment by YYH201905555510** [comment]
1
